CREATE TABLE IF NOT EXISTS public."USERS" (
  "UserID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Username" text NOT NULL UNIQUE,
  "PasswordHash" text NOT NULL,
  "FullName" text NOT NULL,
  "Email" text NOT NULL,
  "Role" text NOT NULL DEFAULT 'ITStaff' CHECK ("Role" IN ('Admin', 'ITStaff')),
  "CreatedAt" timestamptz NOT NULL DEFAULT now(),
  "ContactNumber" text DEFAULT ''
);
CREATE UNIQUE INDEX IF NOT EXISTS users_email_unique ON public."USERS" (lower("Email"));
CREATE TABLE IF NOT EXISTS public."LOCATION" (
  "LocationID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "BuildingName" text,
  "Floor" text,
  "Room" text,
  "Description" text,
  "Coordinates" text
);
CREATE TABLE IF NOT EXISTS public."DEVICE" (
  "DeviceID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "DeviceName" text,
  "DeviceType" text,
  "IPAddress" text UNIQUE,
  "MACAddress" text UNIQUE,
  "Manufacturer" text,
  "Model" text,
  "Status" text NOT NULL DEFAULT 'Offline',
  "LastSeen" timestamptz,
  "CreatedAt" timestamptz NOT NULL DEFAULT now(),
  "Coordinates" text,
  "LocationID" integer REFERENCES public."LOCATION" ("LocationID") ON DELETE SET NULL
);
CREATE TABLE IF NOT EXISTS public."DEVICE_LOG" (
  "LogID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "DeviceID" integer NOT NULL REFERENCES public."DEVICE" ("DeviceID") ON DELETE CASCADE,
  "Timestamp" timestamptz NOT NULL DEFAULT now(),
  "Status" text NOT NULL,
  "IPAddress" text,
  "ConnectivityDetails" text,
  "ScanMethod" text,
  "LatencyMs" numeric,
  "CreatedAt" timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS public."DEVICE_CONNECTION" (
  "ConnectionID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "SourceDeviceID" integer NOT NULL REFERENCES public."DEVICE" ("DeviceID") ON DELETE CASCADE,
  "TargetDeviceID" integer NOT NULL REFERENCES public."DEVICE" ("DeviceID") ON DELETE CASCADE,
  "ConnectionType" text,
  "PortInfo" text,
  "IsActive" smallint NOT NULL DEFAULT 1 CHECK ("IsActive" IN (0, 1)),
  UNIQUE ("SourceDeviceID", "TargetDeviceID", "PortInfo")
);
CREATE TABLE IF NOT EXISTS public."ALERT" (
  "AlertID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "DeviceID" integer REFERENCES public."DEVICE" ("DeviceID") ON DELETE CASCADE,
  "AlertType" text NOT NULL DEFAULT 'other',
  "Severity" text NOT NULL,
  "Issue" text NOT NULL,
  "Timestamp" timestamptz NOT NULL DEFAULT now(),
  "IsResolved" smallint NOT NULL DEFAULT 0 CHECK ("IsResolved" IN (0, 1)),
  "ResolvedByUserID" integer REFERENCES public."USERS" ("UserID") ON DELETE SET NULL,
  "ResolvedAt" timestamptz,
  "ResolutionNotes" text
);
CREATE TABLE IF NOT EXISTS public.activity_logs (
  "LogID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "UserID" integer REFERENCES public."USERS" ("UserID") ON DELETE SET NULL,
  "FullName" text,
  "Action" text NOT NULL,
  "Details" text,
  "IPAddress" text,
  "CreatedAt" timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_device_log_created ON public."DEVICE_LOG" ("CreatedAt");
CREATE INDEX IF NOT EXISTS idx_device_log_device_created ON public."DEVICE_LOG" ("DeviceID", "CreatedAt");
CREATE INDEX IF NOT EXISTS idx_alert_timestamp ON public."ALERT" ("Timestamp");
CREATE INDEX IF NOT EXISTS idx_actlog_created ON public.activity_logs ("CreatedAt");
CREATE INDEX IF NOT EXISTS idx_actlog_user ON public.activity_logs ("UserID");

-- Access is through the Express backend and its existing session/role checks.
-- Browser API keys cannot read password hashes or any other application data.
ALTER TABLE public."USERS" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."LOCATION" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."DEVICE" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."DEVICE_LOG" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."DEVICE_CONNECTION" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."ALERT" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.activity_logs ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."USERS", public."LOCATION", public."DEVICE", public."DEVICE_LOG", public."DEVICE_CONNECTION", public."ALERT", public.activity_logs FROM anon, authenticated;
